//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageLibrary {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LanguageLibrary.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на INFO.
        /// </summary>
        public static string _INFO {
            get {
                return ResourceManager.GetString("_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на set.
        /// </summary>
        public static string _set {
            get {
                return ResourceManager.GetString("_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на add.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add category.
        /// </summary>
        public static string AddCategory {
            get {
                return ResourceManager.GetString("AddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add competitor.
        /// </summary>
        public static string AddCompetitor {
            get {
                return ResourceManager.GetString("AddCompetitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add to category.
        /// </summary>
        public static string AddToCategory {
            get {
                return ResourceManager.GetString("AddToCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AKA Kiken.
        /// </summary>
        public static string AKAKiken {
            get {
                return ResourceManager.GetString("AKAKiken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AKA Shikaku.
        /// </summary>
        public static string AKAShikakau {
            get {
                return ResourceManager.GetString("AKAShikakau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AO Kiken.
        /// </summary>
        public static string AOKiken {
            get {
                return ResourceManager.GetString("AOKiken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AO Shikaku.
        /// </summary>
        public static string AOShikaku {
            get {
                return ResourceManager.GetString("AOShikaku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Auto load next match.
        /// </summary>
        public static string AutoLoadNextMatch {
            get {
                return ResourceManager.GetString("AutoLoadNextMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can&apos;t swap competitors.
        /// </summary>
        public static string CantSwapCompetitors {
            get {
                return ResourceManager.GetString("CantSwapCompetitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Category exproted to file.
        /// </summary>
        public static string CategoryExportedToFile {
            get {
                return ResourceManager.GetString("CategoryExportedToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Category Generator.
        /// </summary>
        public static string CategoryGenerator {
            get {
                return ResourceManager.GetString("CategoryGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Category name.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Category type.
        /// </summary>
        public static string CategoryType {
            get {
                return ResourceManager.GetString("CategoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose default data path.
        /// </summary>
        public static string ChooseDefaultDataPath {
            get {
                return ResourceManager.GetString("ChooseDefaultDataPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear Log.
        /// </summary>
        public static string ClearLog {
            get {
                return ResourceManager.GetString("ClearLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close ext..
        /// </summary>
        public static string CloseExt {
            get {
                return ResourceManager.GetString("CloseExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close external board.
        /// </summary>
        public static string CloseExternalBoard {
            get {
                return ResourceManager.GetString("CloseExternalBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close external results board.
        /// </summary>
        public static string CloseExternalResultsBoard {
            get {
                return ResourceManager.GetString("CloseExternalResultsBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Club.
        /// </summary>
        public static string Club {
            get {
                return ResourceManager.GetString("Club", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Competitors in category.
        /// </summary>
        public static string CompetitorsInCategory {
            get {
                return ResourceManager.GetString("CompetitorsInCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Competitors swaped.
        /// </summary>
        public static string CompetitorsSwaped {
            get {
                return ResourceManager.GetString("CompetitorsSwaped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Complited.
        /// </summary>
        public static string Complited {
            get {
                return ResourceManager.GetString("Complited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Curent match.
        /// </summary>
        public static string CurentMtach {
            get {
                return ResourceManager.GetString("CurentMtach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Database path.
        /// </summary>
        public static string DatabasePath {
            get {
                return ResourceManager.GetString("DatabasePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data path.
        /// </summary>
        public static string DataPath {
            get {
                return ResourceManager.GetString("DataPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you want to shuffle competitors?.
        /// </summary>
        public static string DoYouWantToShuffleCompetitors {
            get {
                return ResourceManager.GetString("DoYouWantToShuffleCompetitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на End of match sound.
        /// </summary>
        public static string EndOfMatchSound {
            get {
                return ResourceManager.GetString("EndOfMatchSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter name to search....
        /// </summary>
        public static string EnterNameToSearch {
            get {
                return ResourceManager.GetString("EnterNameToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export to file.
        /// </summary>
        public static string ExportToFile {
            get {
                return ResourceManager.GetString("ExportToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на External board design.
        /// </summary>
        public static string ExternalBoardDesign {
            get {
                return ResourceManager.GetString("ExternalBoardDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Externals.
        /// </summary>
        public static string Externals {
            get {
                return ResourceManager.GetString("Externals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на External screen.
        /// </summary>
        public static string ExternalScreen {
            get {
                return ResourceManager.GetString("ExternalScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ext. Timer.
        /// </summary>
        public static string ExtTimer {
            get {
                return ResourceManager.GetString("ExtTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Finish.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Finish match.
        /// </summary>
        public static string FinishMatch {
            get {
                return ResourceManager.GetString("FinishMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generate category.
        /// </summary>
        public static string GenerateCategory {
            get {
                return ResourceManager.GetString("GenerateCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Have category results.
        /// </summary>
        public static string HaveCategoryResults {
            get {
                return ResourceManager.GetString("HaveCategoryResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ippon.
        /// </summary>
        public static string Ippon {
            get {
                return ResourceManager.GetString("Ippon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Judjes.
        /// </summary>
        public static string Judjes {
            get {
                return ResourceManager.GetString("Judjes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kiken.
        /// </summary>
        public static string kiken {
            get {
                return ResourceManager.GetString("kiken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 10 sec.
        /// </summary>
        public static string Knockout {
            get {
                return ResourceManager.GetString("Knockout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load match.
        /// </summary>
        public static string LoadMatch {
            get {
                return ResourceManager.GetString("LoadMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load without finishing.
        /// </summary>
        public static string LoadWithoutFinishing {
            get {
                return ResourceManager.GetString("LoadWithoutFinishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log file saved.
        /// </summary>
        public static string LogFileSaved {
            get {
                return ResourceManager.GetString("LogFileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Match ended.
        /// </summary>
        public static string MatchEnded {
            get {
                return ResourceManager.GetString("MatchEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Matches.
        /// </summary>
        public static string Matches {
            get {
                return ResourceManager.GetString("Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Match loaded.
        /// </summary>
        public static string MatchLodaed {
            get {
                return ResourceManager.GetString("MatchLodaed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Match reseted.
        /// </summary>
        public static string MatchRested {
            get {
                return ResourceManager.GetString("MatchRested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Match results saved.
        /// </summary>
        public static string MatchResultsSaved {
            get {
                return ResourceManager.GetString("MatchResultsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Match ended with tie.
        /// </summary>
        public static string MatchTie {
            get {
                return ResourceManager.GetString("MatchTie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Match winner.
        /// </summary>
        public static string MatchWinner {
            get {
                return ResourceManager.GetString("MatchWinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Next match.
        /// </summary>
        public static string NextMatch {
            get {
                return ResourceManager.GetString("NextMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not Complited.
        /// </summary>
        public static string NotComplited {
            get {
                return ResourceManager.GetString("NotComplited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open category.
        /// </summary>
        public static string OpenCategory {
            get {
                return ResourceManager.GetString("OpenCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have currently loaded category. Do you want to open new?.
        /// </summary>
        public static string OpenNewCategory {
            get {
                return ResourceManager.GetString("OpenNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please enter a non empty string.
        /// </summary>
        public static string PleaseEnterANonEmptyString {
            get {
                return ResourceManager.GetString("PleaseEnterANonEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please enter an integer.
        /// </summary>
        public static string PleaseEnterIntgeer {
            get {
                return ResourceManager.GetString("PleaseEnterIntgeer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please wait....
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на point.
        /// </summary>
        public static string point {
            get {
                return ResourceManager.GetString("point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Points.
        /// </summary>
        public static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Primary.
        /// </summary>
        public static string Primary {
            get {
                return ResourceManager.GetString("Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Regenerate.
        /// </summary>
        public static string Regenerate {
            get {
                return ResourceManager.GetString("Regenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Regenerate Bronze stage.
        /// </summary>
        public static string RegerateBronzeStage {
            get {
                return ResourceManager.GetString("RegerateBronzeStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на remove.
        /// </summary>
        public static string remove {
            get {
                return ResourceManager.GetString("remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset Match.
        /// </summary>
        public static string ResetMatch {
            get {
                return ResourceManager.GetString("ResetMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resets.
        /// </summary>
        public static string Resets {
            get {
                return ResourceManager.GetString("Resets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset Timer.
        /// </summary>
        public static string ResetTimer {
            get {
                return ResourceManager.GetString("ResetTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Results.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Round.
        /// </summary>
        public static string Round {
            get {
                return ResourceManager.GetString("Round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Round Robin.
        /// </summary>
        public static string RoundRobin {
            get {
                return ResourceManager.GetString("RoundRobin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rounds.
        /// </summary>
        public static string Rounds {
            get {
                return ResourceManager.GetString("Rounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на sanction.
        /// </summary>
        public static string sanction {
            get {
                return ResourceManager.GetString("sanction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save Log.
        /// </summary>
        public static string SaveLog {
            get {
                return ResourceManager.GetString("SaveLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Senshu.
        /// </summary>
        public static string Senshu {
            get {
                return ResourceManager.GetString("Senshu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set.
        /// </summary>
        public static string Set {
            get {
                return ResourceManager.GetString("Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings saved.
        /// </summary>
        public static string SettingsSaved {
            get {
                return ResourceManager.GetString("SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shikaku.
        /// </summary>
        public static string shikaku {
            get {
                return ResourceManager.GetString("shikaku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show ext..
        /// </summary>
        public static string ShowExt {
            get {
                return ResourceManager.GetString("ShowExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show external board.
        /// </summary>
        public static string ShowExternalBoard {
            get {
                return ResourceManager.GetString("ShowExternalBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show external results board.
        /// </summary>
        public static string ShowExternalResultsBoard {
            get {
                return ResourceManager.GetString("ShowExternalResultsBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show external board with results?.
        /// </summary>
        public static string ShowExternalResultsBoardMessage {
            get {
                return ResourceManager.GetString("ShowExternalResultsBoardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show next match on external board.
        /// </summary>
        public static string ShowNextMatchOnExternalBoard {
            get {
                return ResourceManager.GetString("ShowNextMatchOnExternalBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show results.
        /// </summary>
        public static string ShowResults {
            get {
                return ResourceManager.GetString("ShowResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shuffle.
        /// </summary>
        public static string Shuffle {
            get {
                return ResourceManager.GetString("Shuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Single Elimination (1 third place).
        /// </summary>
        public static string SingleElimination1 {
            get {
                return ResourceManager.GetString("SingleElimination1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Single Elimination (2 third places).
        /// </summary>
        public static string SingleElimination2 {
            get {
                return ResourceManager.GetString("SingleElimination2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Something went wrong.
        /// </summary>
        public static string SmthWentWrong {
            get {
                return ResourceManager.GetString("SmthWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start timer.
        /// </summary>
        public static string StartTmier {
            get {
                return ResourceManager.GetString("StartTmier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stop timer.
        /// </summary>
        public static string StopTmier {
            get {
                return ResourceManager.GetString("StopTmier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Swap.
        /// </summary>
        public static string Swap {
            get {
                return ResourceManager.GetString("Swap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Swap competitors.
        /// </summary>
        public static string SwapCompetitors {
            get {
                return ResourceManager.GetString("SwapCompetitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tatami.
        /// </summary>
        public static string Tatami {
            get {
                return ResourceManager.GetString("Tatami", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This competitor is already in category.
        /// </summary>
        public static string ThisCompetitorIsAlreadyInCategory {
            get {
                return ResourceManager.GetString("ThisCompetitorIsAlreadyInCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tie.
        /// </summary>
        public static string Tie {
            get {
                return ResourceManager.GetString("Tie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time left.
        /// </summary>
        public static string Timeleft {
            get {
                return ResourceManager.GetString("Timeleft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tournament.
        /// </summary>
        public static string Tournament {
            get {
                return ResourceManager.GetString("Tournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tournament name.
        /// </summary>
        public static string TournamentName {
            get {
                return ResourceManager.GetString("TournamentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Version 1.
        /// </summary>
        public static string Version1 {
            get {
                return ResourceManager.GetString("Version1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Version 2.
        /// </summary>
        public static string Version2 {
            get {
                return ResourceManager.GetString("Version2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на View category.
        /// </summary>
        public static string ViewCategory {
            get {
                return ResourceManager.GetString("ViewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warning sound.
        /// </summary>
        public static string WarningSound {
            get {
                return ResourceManager.GetString("WarningSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wazari.
        /// </summary>
        public static string Wazari {
            get {
                return ResourceManager.GetString("Wazari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Winner.
        /// </summary>
        public static string Winner {
            get {
                return ResourceManager.GetString("Winner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Winner AKA.
        /// </summary>
        public static string WinnerAKA {
            get {
                return ResourceManager.GetString("WinnerAKA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Winner AO.
        /// </summary>
        public static string WinnerAO {
            get {
                return ResourceManager.GetString("WinnerAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Without shuffle.
        /// </summary>
        public static string WithoutShuffle {
            get {
                return ResourceManager.GetString("WithoutShuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have data in this category. Do you want to regenerate category?.
        /// </summary>
        public static string YouHaveDataInThisCategory {
            get {
                return ResourceManager.GetString("YouHaveDataInThisCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You haven&apos;t finished currently loaded match. Do you want to finish it?.
        /// </summary>
        public static string YouHaventFinishCurrentlyLoadedMatch {
            get {
                return ResourceManager.GetString("YouHaventFinishCurrentlyLoadedMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yuko.
        /// </summary>
        public static string Yuko {
            get {
                return ResourceManager.GetString("Yuko", resourceCulture);
            }
        }
    }
}
